TOOLCHAIN_HOST_TASK:append = " nativesdk-pogo nativesdk-jive \
        nativesdk-astor \
	nativesdk-python3-pytango nativesdk-openblas-dev \
	nativesdk-librnmshare-dev nativesdk-librnmdpdk-dev \
	nativesdk-gsl-dev nativesdk-itpp-dev nativesdk-fftw-dev \
	nativesdk-libfit-dev nativesdk-libbufferrt-dev \
	nativesdk-libpylon-dev nativesdk-cpptango-dev \
	nativesdk-net-snmp-dev nativesdk-python3-sinstruments \
	nativesdk-lapack-dev nativesdk-libximc-dev nativesdk-hdf5-dev \
        nativesdk-boogie nativesdk-boost-dev nativesdk-libgccjit-dev \
        nativesdk-muparserx-dev"
