TOOLCHAIN_HOST_TASK:append = " nativesdk-pogo nativesdk-jive \
	nativesdk-python3-pytango nativesdk-openblas-dev \
	nativesdk-librnmshare-dev nativesdk-librnmdpdk-dev \
	nativesdk-gsl-dev nativesdk-itpp-dev nativesdk-fftw-dev \
	nativesdk-libfit-dev nativesdk-libbufferrt-dev \
	nativesdk-libpylon-dev nativesdk-cpptango-dev \
	nativesdk-net-snmp-dev nativesdk-python3-sinstruments \
	nativesdk-a3818-dev nativesdk-caenvmelib-dev \
	nativesdk-lapack-dev nativesdk-libandor2-dev \
	nativesdk-libpdv-dev nativesdk-libhimage-dev \
	nativesdk-libtucam-dev nativesdk-libdcam-dev \
	nativesdk-libximc-dev nativesdk-libandor3-dev \
	nativesdk-libbitflow-dev nativesdk-hdf5-dev"
