require conf/distro/voltumna.conf

DISTRO_NAME = "CCD"
SDK_VENDOR = "-ccdsdk"
TARGET_VENDOR = "-ccd"

# Necessary to add lapack
FORTRAN:forcevariable = ",fortran"
RUNTIMETARGET:append:pn-gcc-runtime = " libquadmath"
