require conf/distro/voltumna.inc

DISTRO_NAME = "CCD"
SDK_VENDOR = "-ccdsdk"
TARGET_VENDOR = "-ccd"

# Avoid build error
BBMASK:append = " \
		meta-amd/meta-amd-bsp/recipes-graphics/mesa/ \
		meta-ti/meta-ti-bsp/recipes-graphics/wayland/ \
		"

# Necessary to add lapack
FORTRAN:forcevariable = ",fortran"
RUNTIMETARGET:append:pn-gcc-runtime = " libquadmath"
